# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calc.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\x12\x04\x63\x61lc\"3\n\rSolverRequest\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\x0c\n\x04sign\x18\x02 \x01(\t\x12\t\n\x01\x62\x18\x03 \x01(\x03\" \n\x0eSolverResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32>\n\x06Solver\x12\x34\n\x05Solve\x12\x13.calc.SolverRequest\x1a\x14.calc.SolverResponse\"\x00\x42\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_SOLVERREQUEST']._serialized_start=20
  _globals['_SOLVERREQUEST']._serialized_end=71
  _globals['_SOLVERRESPONSE']._serialized_start=73
  _globals['_SOLVERRESPONSE']._serialized_end=105
  _globals['_SOLVER']._serialized_start=107
  _globals['_SOLVER']._serialized_end=169
# @@protoc_insertion_point(module_scope)
