// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: api/proto/calc.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SolverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A    int64  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	Sign string `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	B    int64  `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *SolverRequest) Reset() {
	*x = SolverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_calc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolverRequest) ProtoMessage() {}

func (x *SolverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolverRequest.ProtoReflect.Descriptor instead.
func (*SolverRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{0}
}

func (x *SolverRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *SolverRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *SolverRequest) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type SolverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result float64 `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SolverResponse) Reset() {
	*x = SolverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_calc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolverResponse) ProtoMessage() {}

func (x *SolverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolverResponse.ProtoReflect.Descriptor instead.
func (*SolverResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{1}
}

func (x *SolverResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_api_proto_calc_proto protoreflect.FileDescriptor

var file_api_proto_calc_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x6c, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x61, 0x6c, 0x63, 0x22, 0x3f, 0x0a, 0x0d,
	0x53, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a,
	0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12,
	0x0c, 0x0a, 0x01, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x62, 0x22, 0x28, 0x0a,
	0x0e, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x3e, 0x0a, 0x06, 0x53, 0x6f, 0x6c, 0x76, 0x65,
	0x72, 0x12, 0x34, 0x0a, 0x05, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x12, 0x13, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x2e, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_calc_proto_rawDescOnce sync.Once
	file_api_proto_calc_proto_rawDescData = file_api_proto_calc_proto_rawDesc
)

func file_api_proto_calc_proto_rawDescGZIP() []byte {
	file_api_proto_calc_proto_rawDescOnce.Do(func() {
		file_api_proto_calc_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_calc_proto_rawDescData)
	})
	return file_api_proto_calc_proto_rawDescData
}

var file_api_proto_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_calc_proto_goTypes = []any{
	(*SolverRequest)(nil),  // 0: calc.SolverRequest
	(*SolverResponse)(nil), // 1: calc.SolverResponse
}
var file_api_proto_calc_proto_depIdxs = []int32{
	0, // 0: calc.Solver.Solve:input_type -> calc.SolverRequest
	1, // 1: calc.Solver.Solve:output_type -> calc.SolverResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_calc_proto_init() }
func file_api_proto_calc_proto_init() {
	if File_api_proto_calc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_calc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SolverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_calc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SolverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_calc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_calc_proto_goTypes,
		DependencyIndexes: file_api_proto_calc_proto_depIdxs,
		MessageInfos:      file_api_proto_calc_proto_msgTypes,
	}.Build()
	File_api_proto_calc_proto = out.File
	file_api_proto_calc_proto_rawDesc = nil
	file_api_proto_calc_proto_goTypes = nil
	file_api_proto_calc_proto_depIdxs = nil
}
